from typing import List, Optional
from pydantic import BaseModel, Field


class PatientProfile(BaseModel):
    age: Optional[int] = Field(None, description="Patient age in years")
    is_pregnant: Optional[bool] = Field(False, description="Whether the patient is pregnant")
    is_breastfeeding: Optional[bool] = Field(False, description="Whether the patient is breastfeeding")
    known_allergies: Optional[List[str]] = Field(default_factory=list, description="Known allergies e.g. ['honey', 'pollen']")
    chronic_conditions: Optional[List[str]] = Field(default_factory=list, description="Chronic conditions e.g. ['hypertension', 'diabetes', 'gallstones']")
    current_medications: Optional[List[str]] = Field(default_factory=list, description="Current medicines e.g. ['blood thinners', 'aspirin']")


class ConsultRequest(BaseModel):
    query: str = Field(..., description="User's description of their symptoms or illness")
    patient_profile: Optional[PatientProfile] = Field(default_factory=PatientProfile, description="Optional patient profile for safety checks")


class RemedyRecommendation(BaseModel):
    remedy_name: str
    ingredients: List[str]
    preparation: str
    dosage: str
    benefits: str


class ConsultResponse(BaseModel):
    identified_symptoms: List[str]
    patient_warnings: List[str] = []
    recommended_remedies: List[RemedyRecommendation]
    critical_precautions: List[str] = Field(..., description="Mandatory warnings & who must avoid this combination")
    who_should_avoid: List[str] = Field(..., description="Strict list of demographics/conditions contraindicated")
    when_to_seek_doctor: List[str] = Field(..., description="Red flag emergency symptoms")
    full_advice_markdown: str
    disclaimer: str = (
        "Medical Disclaimer: This advice is generated by an AI assistant based on natural home remedies "
        "and is for informational purposes only. It is NOT a substitute for professional medical advice, "
        "diagnosis, or treatment. If you experience severe symptoms, high fever, difficulty breathing, "
        "or allergic reactions, consult a certified physician immediately."
    )
